spring.application.name=age-calculator

server.port=${PORT:8080}
spring.datasource.url=https://heinzafxwbmoskpgclkv.supabase.co

spring.datasource.username=age_caculator
spring.datasource.password=Y0mvDmxRUlOy5jdH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect