spring.application.name=age-calculator

server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.heinzafxwbmoskpgclkv&password=i00xMPwO3cOT8sbM

spring.datasource.username=postgres.heinzafxwbmoskpgclkv
spring.datasource.password=i00xMPwO3cOT8sbM
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=update